### ISSUE TITLE
Ram instanciation syntax enhancement

### ISSUE THREAD

**Issue by Nicolasp38** [jandecaluwe/myhdl#143]
When declaring a list for use as RAM, the following syntax works :
    ram = [Signal(intbv(0)[24:]) for i in range(addra.max)]

However, the following syntax, which is much more convenient and equivalent, does not work :
    ram = [Signal(intbv(0)[24:])] * addra.max

It would be cool to be able to use second syntax.

**Comment by jandecaluwe** [comment]
They are not equivalent at all, the second syntax is definitely not what you want.

**Comment by Nicolasp38** [comment]
Can you elaborate on this ?

**Comment by jandecaluwe** [comment]
http://www.jandecaluwe.com/blog/its-a-simulation-language.html

**Comment by NagabhushanS** [comment]
Exactly, the second statement instantiates the list with all the elements being the same object. So, if we  change any element, all the elements of the list will be modified.
