### ISSUE TITLE
Local variables raise an exception in simulation

### ISSUE THREAD

**Issue by ThorimMB** [jandecaluwe/myhdl#146]
The following code raises an exception in simulation in the line "@instance" because the name "diffcode" is not in self.data.symdict (_resolverefs.py, line 51).
I have this problem at several helper variables in different test functions.

```python
from myhdl import intbv, Signal, \
  always_comb, delay, instance, Simulation
from myhdl import bin as mbin

def bin2gray(binary, gray, width):
  @always_comb
  def logic():
    bin_ext = intbv(0)[width+1:]
    bin_ext[:] = binary

    for i in range(width):
      gray.next[i] = bin_ext[i+1] ^ bin_ext[i]

  return logic

def test():
    for width in range(1, 11):
      def test_impl():
        binary = Signal(intbv(0)[width:])
        gray   = Signal(intbv(0)[width:])
        dut = bin2gray(binary, gray, width)

        @instance
        def test():
          binary.next = intbv(0)
          l_temp = Signal(intbv(0))
          yield delay(10)

          for i in range(1, 2**width):
            l_temp.next = gray
            binary.next = intbv(i)
            yield delay(10)
            diffcode = mbin(gray ^ l_temp)
            assert diffcode.count('1') == 1

        return dut, test

      Simulation( test_impl() ).run()

test()
```

Can be fixed by modifying _resolverefs.py and adding a check if the key exists in the dict:
```python
        if not isinstance(node.value, ast.Name):
            return node

        if not node.value.id in self.data.symdict:
            return node

        obj = self.data.symdict[node.value.id]
```
This local helper variables are no signals because they are only used to check test results. I think they can easily by ignored by checking the AST.

Best regards,
Marc

edit:
This problem is new with the current Github version, my older version from 10/10/15 doesn't show this behaviour.

edit2:
I just saw that the same bugfix is in https://github.com/jandecaluwe/myhdl/pull/88/files

**Comment by jandecaluwe** [comment]
Probably this was addressed in commit 755d2b8c that I had not pushed yet.
