### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kiddick** [jandecaluwe/myhdl#151]
On this page [Google Summer of Code 2016](http://dev.myhdl.org/gsoc/gsoc_2016.html) there is the broken link
>The following is a list of additional examples and projects that can be used as first exercises and references:

    *MyHDL Examples*
    MyHDL List of Resources

http://www.myhdl.org/examples/

**Comment by cfelton** [comment]
Thanks for pointing this out.

This repository is specifically for the myhdl code base.  Side problems can be created on the [site repo](https://github.com/myhdl/site-myhdl-dev)

**Comment by kiddick** [comment]
I've mentioned about that issue on site repo https://github.com/jandecaluwe/site-myhdl-dev-retired/issues/2

**Comment by cfelton** [comment]
@kiddick that is the wrong repo, whey the "retired", the correct repo (as linked in the first comment) is https://github.com/myhdl/site-myhdl-dev

**Comment by kiddick** [comment]
@cfelton but there is no section "issues" in forked repos on github :smile:

**Comment by cfelton** [comment]
@kiddick good point, fair enough.  I have updated the link.  Will need to figure out future process.

@jandecaluwe this issue can be closed.
