### ISSUE TITLE
make icarus fails in test/bugs if ghdl is not installed.

### ISSUE THREAD

**Issue by jck** [jandecaluwe/myhdl#27]
https://travis-ci.org/jck/myhdl/jobs/53907805#L400

**Comment by udara28** [comment]
I found that test fails when trying conversion.analyz, to fix this I added a new line to icarus.py which set analyze.simulator to icarus. I submitted a patch <a href="https://github.com/jandecaluwe/myhdl/pull/50">https://github.com/jandecaluwe/myhdl/pull/50</a> as a fix for this issue.

**Comment by jandecaluwe** [comment]
Cherry-picked relevant commit from #50.
