### ISSUE TITLE
Cosimulation error with python 3.2

### ISSUE THREAD

**Issue by alexforencich** [jandecaluwe/myhdl#38]
MyHDL does not seem to like running with Python 3 earlier than 3.4:

            # New pipes are not inheritable by default since py 3.4
            if not PY2:
                for p in rt, wt, rf, wf:
    >               os.set_inheritable(p, True)
    E               AttributeError: 'module' object has no attribute 'set_inheritable'
    
    /usr/local/lib/python3.2/dist-packages/myhdl/_Cosimulation.py:61: AttributeError

**Comment by jandecaluwe** [comment]
I propose to make Python 3.4 the first version to support with MyHDL.

**Comment by jmgc** [comment]
For me it’s ok.

**Comment by jck** [comment]
I'm OK with python 3.4 being the minimum 3.x version we support.
